import { formatGroupedNumber, formatPrice as formatPriceValue } from './price-formatting';
import type { SaleListing, WantedListing } from './types';

// Расширенные данные для B2B
export const saleListings: SaleListing[] = [
  {
    id: '1',
    type: 'sale',
    make: 'Лада',
    model: 'Искра',
    generation: 'I',
    year: 2025,
    price: 1290000,
    priceInHand: 1250000,
    city: 'Белгород',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&h=600&fit=crop',
    ],
    engine: '1.6 л / Бензин',
    power: 106,
    transmission: 'Вариатор',
    drive: 'Передний',
    bodyType: 'Хэтчбек',
    mileage: 1200,
    owners: 1,
    ptsOriginal: true,
    paintCount: 0,
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Белый',
    steering: 'Левый',
    trim: 'Comfort',
    vin: 'XTA21****0012****',
    description: 'Автомобиль куплен новым. Один владелец, все ТО по регламенту. Комплектация Comfort.',
    seller: { id: 's1', name: 'Алексей', type: 'person', verified: true, onPlatformSince: '2023', phone: '+7 (999) ***-**-12' },
    createdAt: '2025-03-15',
    viewCount: 0,
  },
  {
    id: '2',
    type: 'sale',
    make: 'Skoda',
    model: 'Rapid',
    generation: 'II',
    year: 2021,
    price: 1850000,
    priceInHand: 1820000,
    priceOnResources: 1890000,
    city: 'Москва',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop',
    ],
    engine: '1.6 л / Бензин',
    power: 110,
    transmission: 'АКПП',
    drive: 'Передний',
    bodyType: 'Лифтбек',
    mileage: 45000,
    owners: 2,
    ptsOriginal: true,
    paintCount: 0,
    avtotekaStatus: 'green',
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'on_resources',
    sellerType: 'flip',
    color: 'Серый',
    steering: 'Левый',
    trim: 'Style',
    vin: 'XW8ZZ****1234****',
    description: 'Skoda Rapid в отличном состоянии. Полностью обслужен. Резина новая, тормоза в идеале.',
    seller: { id: 's2', name: 'АвтоМир Москва', type: 'company', verified: true, onPlatformSince: '2020' },
    createdAt: '2025-03-18',
    viewCount: 0,
  },
  {
    id: '3',
    type: 'sale',
    make: 'Toyota',
    model: 'Mark X',
    generation: 'II (X130)',
    year: 2017,
    price: 2150000,
    priceInHand: 2100000,
    city: 'Владивосток',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop'],
    engine: '2.5 л / Бензин',
    power: 203,
    transmission: 'АКПП',
    drive: 'Задний',
    bodyType: 'Седан',
    mileage: 78000,
    owners: 2,
    ptsOriginal: true,
    paintCount: 0,
    avtotekaStatus: 'green',
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'pre_resources',
    sellerType: 'owner',
    color: 'Чёрный',
    steering: 'Правый',
    trim: 'Premium',
    vin: 'GRX13****5678****',
    description: 'Toyota Mark X в максимальной комплектации. Правый руль, документы в порядке.',
    seller: { id: 's3', name: 'Дмитрий', type: 'person', verified: true, onPlatformSince: '2024' },
    createdAt: '2025-03-10',
    viewCount: 0,
  },
  {
    id: '4',
    type: 'sale',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    generation: 'W204',
    year: 2011,
    price: 1350000,
    city: 'Санкт-Петербург',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop'],
    engine: '1.8 л / Бензин',
    power: 184,
    transmission: 'АКПП',
    drive: 'Задний',
    bodyType: 'Седан',
    mileage: 156000,
    owners: 3,
    ptsOriginal: true,
    paintCount: 1,
    paintedElements: ['задний бампер'],
    avtotekaStatus: 'yellow',
    taxi: false,
    carsharing: false,
    keysCount: 1,
    needsInvestment: true,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Серебристый',
    steering: 'Левый',
    trim: 'Avantgarde',
    description: 'Mercedes C180 W204. Обслуживался у официалов. Требуется покраска заднего бампера.',
    seller: { id: 's4', name: 'Сергей', type: 'person', verified: false, onPlatformSince: '2022' },
    createdAt: '2025-03-12',
    viewCount: 0,
  },
  {
    id: '5',
    type: 'sale',
    make: 'Skoda',
    model: 'Octavia',
    generation: 'A7 (III)',
    year: 2018,
    price: 1750000,
    priceInHand: 1720000,
    city: 'Краснодар',
    images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop'],
    engine: '1.4 л / Бензин',
    power: 150,
    transmission: 'Робот',
    drive: 'Передний',
    bodyType: 'Лифтбек',
    mileage: 89000,
    owners: 1,
    ptsOriginal: true,
    paintCount: 0,
    avtotekaStatus: 'green',
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Синий',
    steering: 'Левый',
    trim: 'Style',
    description: 'Octavia A7 в идеальном состоянии. Один владелец, DSG без нареканий.',
    seller: { id: 's5', name: 'Игорь', type: 'person', verified: true, onPlatformSince: '2023' },
    createdAt: '2025-03-17',
    viewCount: 0,
  },
  {
    id: '6',
    type: 'sale',
    make: 'Лада',
    model: '2112',
    generation: 'I',
    year: 2008,
    price: 180000,
    city: 'Воронеж',
    images: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop'],
    engine: '1.6 л / Бензин',
    power: 89,
    transmission: 'МКПП',
    drive: 'Передний',
    bodyType: 'Хэтчбек',
    mileage: 198000,
    owners: 4,
    ptsOriginal: true,
    paintCount: 2,
    taxi: false,
    carsharing: false,
    needsInvestment: true,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Зелёный',
    steering: 'Левый',
    trim: 'Стандарт',
    description: '2112 в рабочем состоянии. Требует небольших вложений.',
    seller: { id: 's6', name: 'Виктор', type: 'person', verified: false, onPlatformSince: '2024' },
    createdAt: '2025-03-14',
    viewCount: 0,
  },
  {
    id: '7',
    type: 'sale',
    make: 'Hyundai',
    model: 'Solaris',
    generation: 'II',
    year: 2020,
    price: 1450000,
    city: 'Екатеринбург',
    images: ['https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop'],
    engine: '1.6 л / Бензин',
    power: 123,
    transmission: 'АКПП',
    drive: 'Передний',
    bodyType: 'Седан',
    mileage: 52000,
    owners: 1,
    ptsOriginal: true,
    paintCount: 0,
    avtotekaStatus: 'green',
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'not_listed',
    sellerType: 'flip',
    color: 'Белый',
    steering: 'Левый',
    trim: 'Elegance',
    description: 'Hyundai Solaris II Elegance. Один владелец, вся история по ключу.',
    seller: { id: 's7', name: 'Автоцентр Урал', type: 'company', verified: true, onPlatformSince: '2019' },
    createdAt: '2025-03-16',
    viewCount: 0,
  },
  {
    id: '8',
    type: 'sale',
    make: 'Kia',
    model: 'Rio',
    generation: 'IV',
    year: 2019,
    price: 1320000,
    city: 'Новосибирск',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop'],
    engine: '1.6 л / Бензин',
    power: 123,
    transmission: 'АКПП',
    drive: 'Передний',
    bodyType: 'Седан',
    mileage: 67000,
    owners: 2,
    ptsOriginal: true,
    paintCount: 0,
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Красный',
    steering: 'Левый',
    trim: 'Prestige',
    description: 'Kia Rio в отличном состоянии.',
    seller: { id: 's8', name: 'Андрей', type: 'person', verified: true, onPlatformSince: '2023' },
    createdAt: '2025-03-19',
    viewCount: 0,
  },
  {
    id: '9',
    type: 'sale',
    make: 'Toyota',
    model: 'Land Cruiser',
    generation: '300 Series',
    year: 2022,
    price: 8900000,
    priceInHand: 8750000,
    priceOnResources: 9050000,
    city: 'Москва',
    images: ['/cars/cruiser/cruiser.jpg', '/cars/cruiser/cruiser1.jpg', '/cars/cruiser/cruiser2.jpg'],
    videoUrl: '/cars/cruiser/cruiser.MOV',
    interiorImages: ['/cars/cruiser/salon/salon.jpg'],
    reportUrl: '/cars/cruiser/land_cruiser_300_moscow.pdf',
    engine: '3.5 л / Бензин',
    power: 415,
    transmission: 'АКПП',
    drive: 'Полный',
    bodyType: 'Внедорожник',
    mileage: 32000,
    owners: 1,
    ptsOriginal: true,
    paintCount: 0,
    avtotekaStatus: 'green',
    taxi: false,
    carsharing: false,
    keysCount: 2,
    resourceStatus: 'not_listed',
    sellerType: 'owner',
    color: 'Чёрный',
    steering: 'Левый',
    trim: 'Executive Lounge',
    vin: 'JTMHX3J2****0001',
    description: 'Land Cruiser 300 Executive Lounge. Один владелец, куплен новым. Состояние — новый автомобиль.',
    seller: { id: 's9', name: 'Михаил', type: 'person', verified: true, onPlatformSince: '2022', phone: '+7 (999) ***-**-09' },
    createdAt: '2025-03-20',
    viewCount: 0,
  },
];

export const wantedListings: WantedListing[] = [
  {
    id: 'w1',
    type: 'wanted',
    models: ['Toyota Camry'],
    budgetMax: 2500000,
    budgetMin: 2000000,
    yearFrom: 2019,
    mileageMax: 80000,
    engine: '2.0 / 2.5',
    transmission: 'АКПП',
    ownersMax: 2,
    paintAllowed: false,
    restrictions: ['Не такси', 'Не каршеринг', 'Не салоны', 'Автотека чистая'],
    region: 'Москва и МО',
    comment: 'Ищу под себя, ликвид. Без окрасов приоритет. Присылать с автотекой.',
    contact: 'tg/@flipper',
    author: { id: 's1', name: 'Алексей', type: 'person', verified: true, onPlatformSince: '2023' },
    createdAt: '2025-03-22',
  },
  {
    id: 'w2',
    type: 'wanted',
    models: ['Skoda Octavia A7', 'Volkswagen Jetta 6'],
    budgetMax: 1800000,
    budgetMin: 1400000,
    yearFrom: 2017,
    mileageMax: 100000,
    engine: '1.4 / 1.6 / 1.8',
    transmission: 'Робот / АКПП',
    drive: 'Передний',
    ownersMax: 3,
    paintAllowed: false,
    restrictions: ['Не такси', 'Не каршеринг', 'DSG без нареканий', 'Не битые'],
    region: 'Санкт-Петербург и ЛО',
    comment: 'Для перепродажи. Нужен чистый, без вложений. Документы оригинальные.',
    contact: '+7 (921) ***-**-77',
    author: { id: 's2', name: 'Николай', type: 'person', verified: true, onPlatformSince: '2022' },
    createdAt: '2025-03-21',
  },
  {
    id: 'w3',
    type: 'wanted',
    models: ['Toyota Land Cruiser 200', 'Toyota Land Cruiser Prado 150'],
    budgetMax: 6500000,
    budgetMin: 4500000,
    yearFrom: 2015,
    mileageMax: 120000,
    engine: '4.0 / 4.5',
    transmission: 'АКПП',
    drive: 'Полный',
    ownersMax: 2,
    paintAllowed: false,
    restrictions: ['Не такси', 'Не каршеринг', 'Не Китай', 'Только оригинальное ПТС', 'Только собственник'],
    region: 'Москва и МО',
    comment: 'Под клиента. Состояние только отличное. Смотрю быстро, беру сразу.',
    contact: 'tg/@premium_auto',
    author: { id: 's9', name: 'Михаил', type: 'person', verified: true, onPlatformSince: '2022' },
    createdAt: '2025-03-20',
  },
  {
    id: 'w4',
    type: 'wanted',
    models: ['Hyundai Solaris II', 'Kia Rio IV'],
    budgetMax: 1500000,
    budgetMin: 1100000,
    yearFrom: 2018,
    mileageMax: 90000,
    engine: '1.6',
    transmission: 'АКПП',
    ownersMax: 2,
    paintAllowed: false,
    restrictions: ['Не такси', 'Не каршеринг', 'Без ДТП'],
    region: 'Краснодар и ЮФО',
    comment: 'Массовый ликвид. Беру несколько штук.',
    contact: '+7 (918) ***-**-03',
    author: { id: 's5', name: 'Игорь', type: 'person', verified: true, onPlatformSince: '2021' },
    createdAt: '2025-03-19',
  },
  {
    id: 'w5',
    type: 'wanted',
    models: ['Mercedes-Benz E-Class W212', 'BMW 5 Series F10'],
    budgetMax: 2200000,
    budgetMin: 1600000,
    yearFrom: 2013,
    mileageMax: 150000,
    engine: '2.0 / 2.5',
    transmission: 'АКПП',
    drive: 'Задний',
    ownersMax: 3,
    paintAllowed: true,
    restrictions: ['Не такси', 'Не каршеринг', 'ПТС оригинал'],
    region: 'Любой регион',
    comment: 'Под разборку или восстановление. Рассматриваю варианты с историей.',
    contact: 'tg/@parts_dealer',
    author: { id: 's4', name: 'Сергей', type: 'person', verified: false, onPlatformSince: '2023' },
    createdAt: '2025-03-18',
  },
];

export function formatPrice(price: number): string {
  return formatPriceValue(price);
}

export function formatMileage(mileage: number): string {
  return `${formatGroupedNumber(mileage)} км`;
}

// Обратная совместимость: Vehicle для старых компонентов
export interface Vehicle {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number;
  mileage: number;
  city: string;
  imageUrl: string;
  images: string[];
  videoUrl?: string;
  interiorImages?: string[];
  reportUrl?: string;
  engine: string;
  power: number;
  transmission: string;
  drive: string;
  bodyType: string;
  color: string;
  owners: number;
  steering: string;
  generation: string;
  trim: string;
  vin: string;
  verified: boolean;
  priceStatus: 'low' | 'normal' | 'high';
  description: string;
  seller: { type: string; name: string; rating?: number; onPlatformSince: string; verified: boolean; phone?: string };
  createdAt: string;
}

export function saleListingToVehicle(sl: SaleListing): Vehicle {
  const images = sl.images.filter(Boolean);

  return {
    id: sl.id,
    make: sl.make,
    model: sl.model,
    year: sl.year,
    price: sl.price,
    mileage: sl.mileage,
    city: sl.city,
    imageUrl: images[0] ?? '',
    images,
    videoUrl: sl.videoUrl,
    interiorImages: sl.interiorImages,
    reportUrl: sl.reportUrl,
    engine: sl.engine,
    power: sl.power,
    transmission: sl.transmission,
    drive: sl.drive,
    bodyType: sl.bodyType,
    color: sl.color,
    owners: sl.owners,
    steering: sl.steering,
    generation: sl.generation ?? '',
    trim: sl.trim ?? '',
    vin: sl.vin ?? '',
    verified: sl.seller.verified,
    priceStatus: 'normal',
    description: sl.description,
    seller: {
      type: sl.sellerType,
      name: sl.seller.name,
      onPlatformSince: sl.seller.onPlatformSince,
      verified: sl.seller.verified,
      phone: sl.seller.phone,
    },
    createdAt: sl.createdAt,
  };
}

export const vehicles = saleListings.map(saleListingToVehicle);
